### ISSUE TITLE
reuse our own selenoid image which is built with s3 support

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#1]
need our own image with aws s3 support to be start savinf video artifacts to S3 storage as well.

https://aerokube.com/selenoid/latest/#_uploading_files_to_s3
https://aerokube.com/selenoid/latest/#_s3_cli_flags

**Comment by vdelendik** [comment]
zebrunner (branch: develop) switched to use zebrunner/selenoid:1.10.0 docker image which is built with s3 support.
to test this ticket just clone/pull recursively and verify that zebrunner/selenoid:1.10.0 is up and running.
also using auto_screenshot=true and embedded minio storage should work fine for web-demo-test

**Comment by dhreben** [comment]
Verified on develop branch.
To test  to run web-demo-test  used carina-core_version=6.4.1027-SNAPSHOT
