### ISSUE TITLE
be able to integrate minio with cloud storage by tenant

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#13]
in case of reporting deployed in cloud we have to support selenoid setup using tenant names.
at the same time if reporting is enabled we should proceed in regular way without tenant folder

**Comment by vdelendik** [comment]
fixed. to test we have to 
1. setup from develop branch
2. disable reporting, sonarqube and mcloud
-> during setup there should be question about AWS S3 integration like below
```
AWS S3 storage
Region [us-west-1]: ...
Bucket [changeit]: ...
Access key [changeit]: ...
Secret key [changeit]: ...
[Optional] Tenant []: ...
Region: us-west-1
Endpoint: https://s3.us-west-1.amazonaws.com:443
Bucket: ...
Access key: ...
Secret key: ...
Agent key:
Tenant: ...
Continue? y/n [y]:
```

we have to provide valid cloud settings instead of "..."
3. run web demo test with capabilities
`browserName=chrome;enableLog=true;enableMetadata=true`
-> job should be executed, video.mp4, session.log and metada.json should be recorded and published to zebrunner reporting cloud

**Comment by dhreben** [comment]
Verified.

**Test scenario:**

1.setup from develop branch
2.disable reporting, sonarqube and mcloud
3.during setup there should be a question about AWS S3 integration like below:
```
AWS S3 storage
Region [us-west-1]: ...
Bucket [changeit]: ...
Access key [changeit]: ...
Secret key [changeit]: ...
[Optional] Tenant []: ...
Region: us-west-1
Endpoint: https://s3.us-west-1.amazonaws.com:443
Bucket: ...
Access key: ...
Secret key: ...
Agent key:
Tenant: ...
```
4.Open Jenkins
5.Run RegisterOrganization use creds from qaprosoft.farm tenant 
6.Open integration
7. Add Jenkins paths your instance
8.Tap Launcer
9.Run Web-demo test with capabilities:
   - `browserName=chrome;enableLog=true;enableMetadata=true`

**Expected result:** Job  executed, video.mp4, session.log and metada.json recorded and published to zebrunner reporting cloud.
