### ISSUE TITLE
organize ability to override/setup default cli args via .env

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#15]
https://github.com/aerokube/selenoid/blob/master/docs/cli-flags.adoc
need review all logs and organize docker-compose.yml and .env in such way that it will be the easiset way to override something

```
-save-all-logs
    Whether to save all logs without considering capabilities
-capture-driver-logs
    Whether to add driver process logs to Selenoid output
...
```

**Comment by vdelendik** [comment]
done.
12 cli args declared to be able to change quickly via .env:
```
CONTAINER_NETWORK=infra
ENABLE_FILE_UPLOAD=-enable-file-upload
CPU=1.0
MEMORY=1024m
LIMIT=5
RETRY_COUNT=1
SAVE_ALL_LOGS=-save-all-logs

SERVICE_STARTUP_TIMEOUT=30s
SESSION_ATTEMPT_TIMEOUT=30s
SESSION_DELETE_TIMEOUT=30s
TIMEOUT=3m0s
MAX_TIMEOUT=1h0m0s
```

during the testing verify that web tests work fine.

**Comment by okamara** [comment]
Verified and created a separate issue for Web demo test https://github.com/zebrunner/zebrunner/issues/427

**Comment by okamara** [comment]
After upgrade from 1.0 to 1.5 
Open selenoid/env.original ->

TAG_SELENOID=1.10.0

S3_ENDPOINT=http://minio:X000
S3_ACCESS_KEY_ID=value
S3_SECRET=value
S3_REGION=value
S3_BUCKET=value

S3_KEY_PATTERN=value

**Comment by vdelendik** [comment]
pushed latest selenoid into the develop branch of zebrunner. 
test only setup from develop, upgrade steps not implemented yet at all.

**Comment by okamara** [comment]
Verified on develop branch. Fixed.
