### ISSUE TITLE
generate valid readme with details as it became independent repo starting from v1.2

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#19]
In scope of [#16] selenoid might be configured independently.
So let's generate readme about what is it, on each components it is built (selenoid from aerokube) and quick install/setup guide.
Maybe link onto the GGR to build multi-hosts selenoid cluster

**Comment by vdelendik** [comment]
readme updated for independent usage as well: https://github.com/zebrunner/selenoid/blob/develop/README.md

**Comment by dhreben** [comment]
Verified.
