### ISSUE TITLE
integrate 1.10.8 selenoid to CE

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#41]
https://github.com/aerokube/selenoid/releases/tag/1.10.8

build above version with S3 support and reuse in Zebrunner CE

**Comment by vdelendik** [comment]
done. testing should include CE setup from develop branch and run of the web sample job
-> video recording and selenium logs should be available in reporting

**Comment by okamara** [comment]
Verified on develop branch, fixed.
