### ISSUE TITLE
incorporate upgrade steps into the setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#43]
to move CE upgrade steps (https://github.com/zebrunner/community-edition/issues/491) into the sub-modules we have to support automatic detection of manual intervention inside .env for any value aka:
```
CPU=1.0
MEMORY=1024m
LIMIT=5
RETRY_COUNT=1
SAVE_ALL_LOGS=-save-all-logs

SERVICE_STARTUP_TIMEOUT=30s
SESSION_ATTEMPT_TIMEOUT=30s
SESSION_DELETE_TIMEOUT=30s
TIMEOUT=3m0s
MAX_TIMEOUT=1h0m0s
```

**Comment by vdelendik** [comment]
done. it might be tested during upgrade and using syntenic steps below:
1. setup selenoid independently using branch develop (don't start services)
2. update .env putting non-default values for below vars, for example:
```
CPU=2.0
MEMORY=2024m
LIMIT=6
RETRY_COUNT=2
SAVE_ALL_LOGS=-save-all-logs

SERVICE_STARTUP_TIMEOUT=1m30s
SESSION_ATTEMPT_TIMEOUT=1m30s
SESSION_DELETE_TIMEOUT=1m30s
TIMEOUT=6m0s
MAX_TIMEOUT=1h30m0s
```
3. start and do basic testing of availability of selenoid
4. run `./zebrunner.sh setup` again
-> all custom settings should be saved in .env!

**Comment by okamara** [comment]
Testing will be finished after fix the bug https://github.com/zebrunner/selenoid/issues/44

**Comment by vdelendik** [comment]
testing finished, #44 closed as invalid
