### ISSUE TITLE
During setup independent selenoid "Agent key:" is skipped and user can't enter it value

### ISSUE THREAD

**Issue by okamara** [zebrunner/selenoid#44]
Steps:
1. Clode selenoid via develop branch
2. setup selenoid independently 
Actual result: During setup independent selenoid "Agent key:" is skipped and user can't enter it value, "Agent key:" is not appears before "Tenant"
Expected: "Agent key:" appears before "Tenant"

**Comment by vdelendik** [comment]
not a bug as User Agent is part of CE and reporting. independent selenoid should have only bucket, access and secret keys
