### ISSUE TITLE
Web-demo tests failed with "SessionNotCreated Could not start a new session"

### ISSUE THREAD

**Issue by okamara** [zebrunner/selenoid#47]
Error message from log 
`19:58:10  [ERROR] Failures: 
19:58:10  [ERROR]   WebSampleTest.testBrandGroup:128 » SessionNotCreated Could not start a new session. Unable to parse remote response: You are using Selenoid HEAD!
19:58:10  [ERROR]   WebSampleTest.testCompareModels:79 » SessionNotCreated Could not start a new session. Unable to parse remote response: You are using Selenoid HEAD!
19:58:10  [ERROR]   WebSampleTest.testModelSpecs:55 » SessionNotCreated Could not start a new session. Unable to parse remote response: You are using Selenoid HEAD!
19:58:10  [ERROR]   WebSampleTest.testNewsSearch:104 » SessionNotCreated Could not start a new session. Unable to parse remote response: You are using Selenoid HEAD!`
[consoleText1.txt](https://github.com/zebrunner/pipeline-ce/files/11031735/consoleText1.txt)

**Comment by vdelendik** [comment]
@okamara - re-setup from scratch. I hope upgrading to 1.10.10 selenoid in #46 could solve the problem

**Comment by okamara** [comment]
verified, fixed.
