### ISSUE TITLE
selenoid setup is broken

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#49]
it might be related to the network issue as github.com is not resolved correctly.
let's re-test again doing setup for CE from branch: develop.
-> selenoid should be configured and started successfully.

```
downloading latest chrome/firefox/opera browser images
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by vdelendik** [comment]
closing to re-test when github.com host is resolvable

**Comment by okamara** [comment]
verified, fixed.
