### ISSUE TITLE
bump up to 1.11.2

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#53]
https://github.com/zebrunner/selenoid-fork/pull/3

image:
public.ecr.aws/zebrunner/selenoid:1.11.2

**Comment by vdelendik** [comment]
done. acceptance testing using web-demo job required vs chrome, firefox and edge.
let's try to use carina-demo from master/main with selenium 4 caps...

**Comment by dhreben** [comment]
Verified.

Tested  MicrosoftEdge,Chrome,Firefox browsers
`ZEBRUNNER_VERSION=2.2.1 `
Also added  `overrideFields=capabilities.selenoid:options.enableVideo=true`
Video and Logs are present
