### ISSUE TITLE
escape every dollar using double dollar sign inside .env.original

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#54]
in new version of docker-compose dollars are resolved at the startup. so we have to double each dollar sign to prpvide valid values for s3-key-pattern as minimal

**Comment by vdelendik** [comment]
it should be done as part of the https://github.com/zebrunner/community-edition/issues/587
Using compose as a plugin requires escaping of dollar sigh

**Comment by vdelendik** [comment]
done on stage server already. during the testing we have to verify that video, metadata and session.log are accessibe using eighter s3 so minio storages

**Comment by dhreben** [comment]
Will be test after fix https://github.com/zebrunner/reporting/issues/2357

**Comment by dhreben** [comment]
Basic acceptance successfully completed. Video, screenshots and logs are available.
