### ISSUE TITLE
seenoid session.log file is not accessible

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#56]
we are looking for `https://demo.zebrunner.farm/artifacts/test-sessions/368d0e907c6037ef254fec941bd5e02b/session.log` but file is published as
`https://demo.zebrunner.farm/artifacts/test-sessions/368d0e907c6037ef254fec941bd5e02b/log.log`

we have to find the place where mistake happened, potentially in new default selenoid capabilities

**Comment by vdelendik** [comment]
fixed in scope of 1.11.2 selenoid-fork change: https://github.com/zebrunner/selenoid-fork/commit/df62d76877f8d3cb37298314067ab1cfc128ed4b

changes already in develop branch of CE

**Comment by dhreben** [comment]
Fixed
