### ISSUE TITLE
Video is not working in old test run

### ISSUE THREAD

**Issue by okamara** [zebrunner/selenoid#7]
Testing scenario:

clone zebrunner from master, setup everything and run regression jobs
switched to develop branch and do recurive pull
execute upgrade task
./zebrunner.sh upgrade
restart everything
Open Web demo test and verify that video is working and visible
Actual result: video is not working and not visible

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/selenoid/commit/19c276374d39206cb9783b35fee75baecb9432cf

Restored ./selenoid/video shared folder to show old pre-upgrade videos

**Comment by okamara** [comment]
Verified. Fixed.
