### ISSUE TITLE
rename key pattern for s3 video artifacts to use test-sessions

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/selenoid#9]
https://github.com/zebrunner/selenoid/blob/8a510df74d3caa6ca485cdd089a5a3c86d23a5b0/docker-compose.yml#L18

we want to standardized ce and pro recording locations including mcloud and switch to the 7.x core generation and zebrunner agent

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/selenoid/commit/a7965f9dece77884d9aa9c04de457bba20f4bd4c
changes are pushed into the zebrunner (branch: develop)

during the testing please make sure that inside embedded s3 minio storage video artifacts are saved in new location:
`artifacts/test-sessions/$sessionId/video.mp4`

**Comment by okamara** [comment]
Verified -> /data/zebrunner/artifacts/test-sessions/1668178f12bf76e6dbecb7a61db4edee/video.mp4
